#!/usr/bin/env bash
# mang-arr stack installer: Suwayomi (sources + downloads) + Komga (reader) + mang-arr (manager),
# brought up with Docker Compose and wired together.
#
#   curl -fsSL https://raw.githubusercontent.com/AndrewHuddleston/mang-arr/main/install.sh | bash
#   # or: ./install.sh [--dir DIR] [--data DIR] [--yes]
#
# Environment overrides (all optional):
#   STACK_DIR      where docker-compose.yml and the config folders go   (default ./mang-arr-stack)
#   DATA_DIR       where chapters are stored: <DATA_DIR>/staging (Suwayomi) and <DATA_DIR>/library (Komga)
#                  (default <STACK_DIR>/data; both trees MUST live under this one folder for hard links)
#   PUID / PGID    user the containers run as                            (default: current user)
#   TZ             timezone                                              (default: system or UTC)
#   MANGARR_PORT / SUWAYOMI_PORT / KOMGA_PORT                            (default 6789 / 4567 / 25600)
#   KOMGA_EMAIL / KOMGA_PASSWORD   Komga admin login to create (or to use, if Komga is already claimed)
#   MANGARR_IMAGE  image for mang-arr                                    (default ghcr.io/andrewhuddleston/mang-arr:latest)
#   CONTAINER_PREFIX  prefix for the three container names (default none)
#   SOURCES        Suwayomi extensions to install, comma-separated pkgName suffixes (see DEFAULT_SOURCES)
#   YES=1          no prompts
set -euo pipefail

STACK_DIR="${STACK_DIR:-$PWD/mang-arr-stack}"
DATA_DIR="${DATA_DIR:-}"
PUID="${PUID:-$(id -u)}"
PGID="${PGID:-$(id -g)}"
TZ="${TZ:-$(cat /etc/timezone 2>/dev/null || timedatectl show -p Timezone --value 2>/dev/null || echo UTC)}"
MANGARR_PORT="${MANGARR_PORT:-6789}"
SUWAYOMI_PORT="${SUWAYOMI_PORT:-4567}"
KOMGA_PORT="${KOMGA_PORT:-25600}"
MANGARR_IMAGE="${MANGARR_IMAGE:-ghcr.io/andrewhuddleston/mang-arr:latest}"
CONTAINER_PREFIX="${CONTAINER_PREFIX:-}"
YES="${YES:-0}"
# Suwayomi extensions installed by default (Keiyoushi pkgName suffixes): a mix of
# official platforms and the aggregators that carry the widest English catalogue.
DEFAULT_SOURCES="en.weebcentral,all.mangadex,en.bbato,all.webtoons,all.mangaplus,en.mangakakalotfun,en.manganelo,en.asurascans,en.flamecomics"
SOURCES="${SOURCES:-$DEFAULT_SOURCES}"
EXT_REPO="https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dir) STACK_DIR="$2"; shift 2 ;;
    --data) DATA_DIR="$2"; shift 2 ;;
    --yes|-y) YES=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done
DATA_DIR="${DATA_DIR:-$STACK_DIR/data}"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ok\033[0m  %s\n' "$*"; }
warn() { printf '\033[1;33m !!\033[0m  %s\n' "$*"; }
die()  { printf '\033[1;31mERR\033[0m  %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "$1 is required"; }
need docker; need curl; need python3
docker compose version >/dev/null 2>&1 || die "docker compose (v2) is required"
docker info >/dev/null 2>&1 || die "docker is not running or you cannot access it (try: sudo usermod -aG docker \$USER)"

gql() {  # gql <url> <query-json>
  curl -fsS --max-time 60 -H 'Content-Type: application/json' -d "$2" "$1/api/graphql"
}
jsonget() { python3 -c 'import json,sys;d=json.load(sys.stdin)
for k in sys.argv[1].split("."):
    d = d[int(k)] if isinstance(d, list) else d.get(k)
    if d is None: break
print("" if d is None else (json.dumps(d) if isinstance(d,(dict,list)) else d))' "$1"; }
wait_http() {  # wait_http <url> <seconds> <label>
  local i; for i in $(seq 1 "$2"); do curl -fsS -o /dev/null --max-time 5 "$1" 2>/dev/null && return 0; sleep 2; done
  die "$3 did not come up at $1 within $(( $2 * 2 ))s (docker compose logs $3)"
}

say "mang-arr stack -> $STACK_DIR   data -> $DATA_DIR   user $PUID:$PGID   tz $TZ"
say "ports: mang-arr $MANGARR_PORT, Suwayomi $SUWAYOMI_PORT, Komga $KOMGA_PORT"
if [[ "$YES" != 1 ]]; then read -r -p "continue? [Y/n] " a; [[ "${a:-y}" =~ ^[Yy]?$ ]] || exit 1; fi

# ---------------------------------------------------------------- files
mkdir -p "$STACK_DIR"/{config/mangarr,config/suwayomi,config/komga} "$DATA_DIR"/{staging,library}
chown -R "$PUID:$PGID" "$STACK_DIR/config" "$DATA_DIR" 2>/dev/null || true

if [[ -f "$STACK_DIR/docker-compose.yml" ]]; then
  warn "$STACK_DIR/docker-compose.yml exists; keeping it (delete it to regenerate)"
else
cat > "$STACK_DIR/docker-compose.yml" <<EOF
# Generated by mang-arr install.sh. Three services, one data tree:
#   $DATA_DIR/staging  <- Suwayomi writes chapters here (never renamed)
#   $DATA_DIR/library  <- mang-arr builds the per-series hard-link tree here; Komga reads it
services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: ${CONTAINER_PREFIX}suwayomi
    user: "$PUID:$PGID"
    environment:
      - TZ=$TZ
      - DOWNLOAD_AS_CBZ=true
    volumes:
      - ./config/suwayomi:/home/suwayomi/.local/share/Tachidesk
      - $DATA_DIR/staging:/home/suwayomi/.local/share/Tachidesk/downloads/mangas
    ports:
      - "$SUWAYOMI_PORT:4567"
    restart: unless-stopped

  komga:
    image: gotson/komga:latest
    container_name: ${CONTAINER_PREFIX}komga
    user: "$PUID:$PGID"
    environment:
      - TZ=$TZ
    volumes:
      - ./config/komga:/config
      - $DATA_DIR/library:/library:ro
    ports:
      - "$KOMGA_PORT:25600"
    restart: unless-stopped

  mangarr:
    image: $MANGARR_IMAGE
    container_name: ${CONTAINER_PREFIX}mangarr
    user: "$PUID:$PGID"
    depends_on:
      - suwayomi
    environment:
      - TZ=$TZ
      - MANGARR_SUWAYOMI_URL=http://suwayomi:4567
      - MANGARR_STAGING=/data/staging
      - MANGARR_LIBRARY=/data/library
    volumes:
      - ./config/mangarr:/config
      - $DATA_DIR:/data
    ports:
      - "$MANGARR_PORT:6789"
    restart: unless-stopped
EOF
ok "wrote $STACK_DIR/docker-compose.yml"
fi

# ---------------------------------------------------------------- up
say "pulling images and starting containers"
( cd "$STACK_DIR" && (docker compose pull -q --ignore-pull-failures || warn "some images could not be pulled; using local copies if present") && docker compose up -d )
SUWA="http://127.0.0.1:$SUWAYOMI_PORT"; KOMGA="http://127.0.0.1:$KOMGA_PORT"; MANGARR="http://127.0.0.1:$MANGARR_PORT"
wait_http "$SUWA/api/graphql?query=%7Bsettings%7BdownloadAsCbz%7D%7D" 90 suwayomi; ok "Suwayomi is up"
wait_http "$KOMGA/api/v1/claim" 90 komga; ok "Komga is up"
wait_http "$MANGARR/api/v1/system/status" 60 mangarr; ok "mang-arr is up"

# ---------------------------------------------------------------- suwayomi
say "configuring Suwayomi"
gql "$SUWA" '{"query":"mutation { setSettings(input:{settings:{downloadAsCbz:true, autoDownloadNewChapters:false}}) { settings { downloadAsCbz } } }"}' >/dev/null
ok "chapters saved as CBZ; Suwayomi's own auto-download off (mang-arr drives downloads)"
repos=$( (gql "$SUWA" '{"query":"{ extensionStores { indexUrl } }"}' 2>/dev/null; gql "$SUWA" '{"query":"{ settings { extensionRepos } }"}' 2>/dev/null) | tr -d '\n')
if [[ "$repos" != *keiyoushi* ]]; then
  gql "$SUWA" "{\"query\":\"mutation { addExtensionStore(input:{indexUrl:\\\"$EXT_REPO\\\"}) { clientMutationId } }\"}" >/dev/null 2>&1 \
    || gql "$SUWA" "{\"query\":\"mutation { setSettings(input:{settings:{extensionRepos:[\\\"$EXT_REPO\\\"]}}) { clientMutationId } }\"}" >/dev/null
  ok "extension repository added"
fi
gql "$SUWA" '{"query":"mutation { fetchExtensions(input:{}) { extensions { pkgName } } }"}' >/dev/null 2>&1 || true
# the index is fetched in the background; wait until the catalogue is populated
for i in $(seq 1 30); do
  total=$(gql "$SUWA" '{"query":"{ extensions { totalCount } }"}' | jsonget data.extensions.totalCount)
  [[ "${total:-0}" -gt 0 ]] && break
  sleep 2
done
[[ "${total:-0}" -gt 0 ]] && ok "extension catalogue: $total extensions" || warn "extension catalogue is empty; sources must be installed in Suwayomi's UI"
catalog=$(gql "$SUWA" '{"query":"{ extensions { nodes { pkgName name lang isInstalled isNsfw } } }"}')
IFS=',' read -r -a wanted <<< "$SOURCES"
for suffix in "${wanted[@]}"; do
  line=$(printf '%s' "$catalog" | python3 -c '
import json,sys
suf=sys.argv[1]
for e in json.load(sys.stdin)["data"]["extensions"]["nodes"]:
    if e["pkgName"].endswith("."+suf):        # requested explicitly: the loose NSFW flag in the catalogue does not apply
        print(e["pkgName"], "installed" if e["isInstalled"] else "missing", e["name"]); break' "$suffix")
  [[ -z "$line" ]] && { warn "extension '$suffix' not in the catalogue; skipped"; continue; }
  set -- $line; pkg=$1; state=$2; shift 2; name="$*"
  if [[ "$state" == installed ]]; then ok "$name already installed"; continue; fi
  if gql "$SUWA" "{\"query\":\"mutation { updateExtension(input:{id:\\\"$pkg\\\", patch:{install:true}}) { extension { pkgName isInstalled } } }\"}" >/dev/null 2>&1; then
    ok "installed $name"
  else
    warn "could not install $name ($pkg)"
  fi
done

# ---------------------------------------------------------------- komga
say "configuring Komga"
claimed=$(curl -fsS "$KOMGA/api/v1/claim" | jsonget isClaimed)
if [[ -z "${KOMGA_EMAIL:-}" ]]; then
  if [[ "$YES" == 1 ]]; then KOMGA_EMAIL="admin@example.com"; else read -r -p "Komga admin email [admin@example.com]: " KOMGA_EMAIL; KOMGA_EMAIL="${KOMGA_EMAIL:-admin@example.com}"; fi
fi
if [[ -z "${KOMGA_PASSWORD:-}" ]]; then
  if [[ "$YES" == 1 ]]; then KOMGA_PASSWORD="$(python3 -c 'import secrets;print(secrets.token_urlsafe(12))')"; echo "Komga admin password: $KOMGA_PASSWORD"
  else read -r -s -p "Komga admin password (min 8): " KOMGA_PASSWORD; echo; fi
fi
if [[ "$claimed" == "False" || "$claimed" == "false" ]]; then
  curl -fsS -o /dev/null -X POST -H "X-Komga-Email: $KOMGA_EMAIL" -H "X-Komga-Password: $KOMGA_PASSWORD" "$KOMGA/api/v1/claim" \
    && ok "Komga admin user created ($KOMGA_EMAIL)" || die "could not create the Komga admin user"
else
  ok "Komga already has an admin; using $KOMGA_EMAIL"
fi
komga_key=$(curl -fsS -u "$KOMGA_EMAIL:$KOMGA_PASSWORD" -H 'Content-Type: application/json' -X POST \
  -d '{"comment":"mang-arr"}' "$KOMGA/api/v2/users/me/api-keys" | jsonget key) || die "Komga login failed for $KOMGA_EMAIL"
[[ -n "$komga_key" ]] || die "Komga did not return an API key"
ok "Komga API key for mang-arr created"
lib_id=$(curl -fsS -H "X-API-Key: $komga_key" "$KOMGA/api/v1/libraries" | python3 -c 'import json,sys;print(next((l["id"] for l in json.load(sys.stdin) if l["root"].rstrip("/")=="/library"),""))')
if [[ -z "$lib_id" ]]; then
  lib_id=$(curl -fsS -H "X-API-Key: $komga_key" -H 'Content-Type: application/json' -X POST \
    -d '{"name":"Manga","root":"/library","scanOnStartup":true,"hashFiles":true}' "$KOMGA/api/v1/libraries" | jsonget id)
  ok "Komga library 'Manga' created on /library ($lib_id)"
else
  ok "Komga library on /library exists ($lib_id)"
fi

# ---------------------------------------------------------------- mang-arr
say "configuring mang-arr"
curl -fsS -o /dev/null -X PUT -H 'Content-Type: application/json' "$MANGARR/api/v1/settings" \
  -d "$(python3 -c 'import json,sys;print(json.dumps({"komga_url":"http://komga:25600","komga_api_key":sys.argv[1],"komga_library_id":sys.argv[2]}))' "$komga_key" "$lib_id")" \
  && ok "mang-arr knows Komga (scan after every import)"
health=$(curl -s "$MANGARR/api/v1/health")
echo "$health" | jsonget ok | grep -qi true && ok "mang-arr health: ok" || warn "mang-arr health: $health"

cat <<EOF

$(printf '\033[1;32mDone.\033[0m')
  mang-arr   http://$(hostname -I 2>/dev/null | awk '{print $1}' || echo localhost):$MANGARR_PORT   (Add New, Library Import, Settings)
  Suwayomi   http://localhost:$SUWAYOMI_PORT   (sources; nothing to do here day to day)
  Komga      http://localhost:$KOMGA_PORT   login: $KOMGA_EMAIL

Next:
  * open mang-arr -> Add New, or Library Import if $DATA_DIR/staging already holds chapters
  * Settings -> Security to set a login; Settings -> Notifications for Pushover
  * everything lives in $STACK_DIR (compose file, config/) and $DATA_DIR (chapters)
EOF
